import test from 'node:test';import assert from 'node:assert/strict';
import {Vehicle,CONDITIONS,Circuit} from '../public/simulation.js';
function access(v){v.act('hood','hand');v.act('cover','hand');}
function diagnose(v){access(v);v.act('obd','scanner');v.ignition('KEY ON');v.scan('codes');v.measure('dc','bat+','bat-');v.measure('dc','ref','ground');v.measure('dc','gnd','ground');v.ignition('CRANKING');v.tick(500);v.scan('live');v.waveform('sig','ground');v.release();v.ignition('KEY OFF');v.act('connector','hand');v.act('pcmConnector','hand');v.measure('ohm','sig','pcm');v.act('pcmConnector','hand');}
function repair(v){for(let i=0;i<3;i++)v.act('bolt','socket8');v.act('sensor','hand');v.act('sensor','replacement');for(let i=0;i<3;i++)v.act('bolt','socket8');v.act('connector','hand');}
test('diagnostic measurements and full repair require real circuit/procedure state',()=>{const v=new Vehicle();assert.equal(v.scan('codes').connected,false);diagnose(v);for(const k of ['dtc','battery','reference','ground','rpm','signal','continuity'])assert.ok(v.evidence[k],k);assert.equal(v.measure('ohm','sig','pcm').text,'ISOLATE');repair(v);assert.equal(v.verified,false);v.ignition('CRANKING');v.tick(1500);assert.equal(v.key,'RUNNING');assert.equal(v.rpm(),735);assert.equal(v.dtc,true);v.scan('live');v.clearCodes();v.scan('codes');assert.equal(v.verified,false);v.tick(5000);v.scan('codes');assert.equal(v.verified,true);v.finish();assert.equal(v.complete,true);});
test('repair cannot skip key, access, connector, correct socket, retaining bolt',()=>{const v=new Vehicle();assert.match(v.act('sensor','hand'),/Open/);access(v);assert.match(v.act('bolt','socket8'),/Disconnect/);v.ignition('KEY ON');assert.match(v.act('connector','hand'),/OFF/);v.ignition('KEY OFF');v.act('connector','hand');assert.match(v.act('bolt','wrench10'),/8 mm/);assert.match(v.act('sensor','replacement'),/bolt/);v.act('bolt','socket8');assert.equal(v.bolt,2);assert.equal(v.components.ckp.installed,true);assert.equal(v.verified,false);});
test('measurements change with ignition, polarity, isolation and circuit faults',()=>{const v=new Vehicle();assert.equal(v.measure('dc','ref','ground').value,0);v.ignition('KEY ON');assert.equal(v.measure('dc','ref','ground').value,5.02);assert.equal(v.measure('dc','ground','ref').value,-5.02);assert.equal(v.measure('ohm','sig','pcm').text,'LIVE');v.circuits.reference.condition='open circuit';assert.equal(v.measure('dc','ref','ground').text,'OL');v.circuits.reference.condition='short to power';assert.equal(v.measure('dc','ref','ground').value,v.battery());v.circuits.reference.condition='short to ground';assert.equal(v.measure('dc','ref','ground').value,0);});
test('failed repair and disconnected signal cannot start; early erasure returns code',()=>{const v=new Vehicle();v.act('obd','scanner');v.ignition('KEY ON');v.clearCodes();v.ignition('CRANKING');v.tick(1600);assert.equal(v.rpm(),0);assert.equal(v.dtc,true);v.release();assert.equal(v.key,'KEY ON');v.components.ckp.condition='healthy';v.connectors.ckp.connected=false;v.ignition('CRANKING');v.tick(1600);assert.equal(v.rpm(),0);});
test('all supported fault conditions resolve; circuit failure stalls running engine',()=>{for(const condition of CONDITIONS){const c=new Circuit('signal',condition);assert.ok(c.voltage(5,12,0)===null||Number.isFinite(c.voltage(5,12,0)));}const v=new Vehicle();v.components.ckp.condition='healthy';v.ignition('CRANKING');v.tick(1500);assert.equal(v.key,'RUNNING');v.circuits.signal.condition='open circuit';v.tick(100);assert.equal(v.key,'STALLED');});
test('meter current fuse opens across supply; signal resistance needs isolation',()=>{const v=new Vehicle();assert.equal(v.measure('amps','bat+','bat-').text,'FUSE');assert.equal(v.meterFuse,false);assert.equal(v.measure('ohm','sig','pcm').text,'ISOLATE');v.connectors.ckp.connected=false;v.connectors.pcm.connected=false;assert.equal(v.measure('ohm','sig','pcm').value,.3);v.circuits.signal.condition='high resistance';assert.equal(v.measure('ohm','sig','pcm').value,180);});
test('scope responds to actual leads, rotation and signal generation',()=>{const v=new Vehicle();assert.equal(v.waveform('sig',null).connected,false);v.ignition('CRANKING');assert.equal(v.waveform('sig','ground').active,false);assert.equal(v.waveform('cmp','ground').active,true);v.components.ckp.condition='healthy';assert.equal(v.waveform('sig','ground').active,true);v.connectors.ckp.connected=false;assert.equal(v.waveform('sig','ground').active,false);});
test('battery, fuse and relay affect power and behavior',()=>{const v=new Vehicle();v.ignition('KEY ON');assert.equal(v.fuel(),42);v.components.relay.installed=false;assert.equal(v.fuel(),0);v.components.fuse.installed=false;assert.equal(v.voltage('ref'),0);v.ignition('KEY OFF');v.act('battery','wrench10');assert.equal(v.ignition('CRANKING'),'Battery disconnected');});
test('compression gauge retains peak and spark tester needs ground and rotation',()=>{const v=new Vehicle();v.coilOut=true;v.plugOut=true;assert.match(v.ignition('CRANKING'),/relay/);v.components.relay.installed=false;v.ignition('CRANKING');v.tick(3200);assert.equal(v.pressure('compression',true),165);v.release();assert.equal(v.pressure('compression',true),165);assert.equal(v.pressure('fuel',false),null);assert.equal(v.spark(true,null),null);assert.equal(v.spark(true,'ground'),false);});
test('passive scanner refresh cannot verify repair without an explicit rescan',()=>{const v=new Vehicle();diagnose(v);repair(v);v.ignition('CRANKING');v.tick(1500);v.scan('live');v.clearCodes();v.tick(6000);v.scan('codes',false);assert.equal(v.verified,false);v.scan('codes');assert.equal(v.verified,true);});
