import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
try{const p=await b.newPage({viewport:{width:1440,height:1000}});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:45637');const click=s=>p.locator(s).click();const tool=id=>click(`[data-tool="${id}"]`);const part=id=>click(`[data-part="${id}"] .outline`);const view=id=>click(`[data-view="${id}"]`);const lead=async(c,id)=>{await click(`[data-lead="${c}"]`);await click(`[data-pin="${id}"] .tip`);};const crank=async(ms)=>{let r=await p.locator('#crank').boundingBox();await p.mouse.move(r.x+20,r.y+20);await p.mouse.down();await p.waitForTimeout(ms);};
await part('hood');await part('cover');await tool('light');await lead('red','bat+');await lead('black','bat-');await p.waitForFunction(()=>document.querySelector('#bulb').classList.contains('lit'));
await tool('scope');await lead('red','cmp');await lead('black','ground');await crank(500);assert.match(await p.locator('#scopeReading').innerText(),/5.0 V peak/);await p.screenshot({path:'test-results/cmp-waveform.png',fullPage:true});await p.mouse.up();await click('#keyOff');
await tool('hand');await part('coilBody');await tool('spark');await click('[data-lead="spark"]');await click('[data-pin="coil"] .tip');await lead('black','ground');await crank(500);assert.match(await p.locator('#sparkReading').innerText(),/No spark while cranking/);await p.mouse.up();await click('#keyOff');
await tool('socket16');await part('plug');await view('fuses');await tool('hand');await part('fuseCover');await part('relay');await view('bay');await tool('compression');await part('plug');await crank(3300);assert.match(await p.locator('#gaugeReading').innerText(),/165 PSI/);await p.mouse.up();assert.match(await p.locator('#gaugeReading').innerText(),/165 PSI/);await p.screenshot({path:'test-results/compression.png',fullPage:true});await click('#keyOff');
await tool('socket16');await part('plug');await tool('hand');await part('coilBody');await view('fuses');await part('relay');await part('fuse');await tool('scanner');await view('interior');await part('obd');await click('#keyOn');assert.match(await p.locator('#scannerScreen').innerText(),/NO RESPONSE/);await click('#keyOff');await tool('hand');await view('fuses');await part('fuse');await tool('wrench10');await view('bay');await part('battery');await click('#keyOn');assert.equal(await p.locator('#engineState').innerText(),'KEY OFF');await part('battery');
assert.deepEqual(errors,[]);console.log('PASS: loaded test light, CMP scope waveform, connected spark tester, prepared compression test, fuse/relay removal and reinstatement, battery wrench');
}finally{await b.close();}
